# Generated by Django 3.2.9 on 2021-11-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('course', models.CharField(choices=[('1', 'Java'), ('2', 'Python'), ('3', 'Javascript')], max_length=15)),
            ],
        ),
    ]
